# Site settings
title: wah-lon-zero
email: sid@rancher.com
description: > # this means to ignore newlines until "baseurl:"
    Hello there! I'm Sid, a developer working on building cool stuff at Rancher Labs
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wlan0.github.io" # the base hostname & protocol for your site
twitter_username: utter_babbage
github_username:  wlan0

# Build settings
markdown: kramdown
