# Site settings
title: Utter Babbage
email: sid@rancher.com
description: > # this means to ignore newlines until "baseurl:"
  Nothing I say will not be utter babbage - the utter babbage guarantee  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sidharthamani.github.io" # the base hostname & protocol for your site
twitter_username: utter_babbage
github_username:  sidharthamani

# Build settings
markdown: kramdown
